# Mod Properties
# Recommended Versioning Scheme: https://docs.neoforged.net/docs/gettingstarted/versioning/
version = 1.2.1-1.21.1
# Your mod id should be descriptive, ideally just your mod's name in all lowercase with no hyphens or underscores.
mod_id = maptip
mod_name = Maptip
# Your group should be a unique identifier in reverse domain format.
group = com.imeetake
description=View maps in tooltips.
# Fill out these URLs with links to your website or project page, sources (if public), issue tracker and Discord invite.
homepage=https://www.curseforge.com/minecraft/mc-mods/maptip
sources=https://github.com/iMeeTake/maptip
issues=https://github.com/iMeeTake/maptip/issues
discord=
# Make sure the license here matches the one you defined in the LICENSE file.
license=MIT
mod_author = iMeeTake
# Credits can include other attribution as well, such as artists, etc.
credits = iMeeTake

# Publishing Properties
# You can find the project ID on the CurseForge / Modrinth project page. You can leave this empty until you publish your mod.
curseforge_release_type = release
curseforge_project_id = 1353735
curseforge_environments = Client
modrinth_release_type = release
modrinth_project_id = maptip
# If you have a Maven to deploy to, configure its URLs here.
# maven_releases = https://
# maven_snapshots = https://

# Minecraft Properties
# The Minecraft version your mod is built against. This is the version of Minecraft that will be loaded into your development environment.
minecraft_version = 1.21.1
# A list of Minecraft versions that your mod supports. This is used as metadata for CurseForge and Modrinth.
minecraft_versions = 1.21.1
# The version range that your mod can run on. It's hard to predict what minor version will introduce breaking changes, so I recommend just setting the next major version as upper limit.
minecraft_version_range = [1.21.1]
# The Java version to use. Different Minecraft versions require different Java versions.
java_version = 21

# Common Properties
# NeoForm is used for setting up Minecraft in the common project. You can find the latest version at: https://projects.neoforged.net/neoforged/neoform
neo_form_version = 1.21.1-20240808.144430
# Parchment adds human-readable names to parameters. You can find the latest version at: https://parchmentmc.org/docs/getting-started
parchment_minecraft = 1.21.1
parchment_version = 2024.11.17

# Balm Properties
# The Balm version to use. You can find all versions on the Maven: https://maven.twelveiterations.com/service/rest/repository/browse/maven-public/net/blay09/mods/balm-common/
# Balm versions follow the NeoForge versioning scheme since Minecraft 1.21.
# For best stability, only use -SNAPSHOT versions if you need access to an unreleased Balm feature.
# balm_version = 21.0.38+1.21.1
balm_version = 21.0.56+1.21.1
# The minimum Balm version to use. You should set this if you are using a Balm feature that is not available in older versions.
# Avoid setting a maximum version - Balm generally does not introduce breaking changes mid-version.
balm_version_range = [21.0.56,)

# NeoForge Properties
# The NeoForge version to use. You can find all versions on their website: https://projects.neoforged.net/neoforged/neoforge
neoforge_version = 21.1.120
neoforge_version_range = [21,)
neoforge_loader_version_range = [1,)

# Fabric Properties
# The Fabric versions to use. You can find the latest version on their website: https://fabricmc.net/develop/
fabric_version = 0.115.0+1.21.1
fabric_loader_version = 0.16.10

# Dependencies
# You can add additional properties here and reference them in your `dependencies.gradle` files.
modmenu_version=11.0.3
mixin_version=0.8.5

# Gradle Properties
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
