modLoader="javafml"
loaderVersion="[1,)"
license="${license}"
issueTrackerURL="${issues}"
[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
displayURL="${homepage}"
logoFile="${mod_id}-icon.png"
credits="${credits}"
authors="${mod_author}"
description='''${description}'''
displayTest="IGNORE_SERVER_VERSION"
[[mixins]]
config="${mod_id}.neoforge.mixins.json"
[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neoforge_version},)"
ordering="NONE"
side="CLIENT"
[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="CLIENT"
[[dependencies.${mod_id}]]
modId="balm"
type="required"
versionRange="[${balm_version},)"
ordering="NONE"
side="CLIENT"
